######################################################################
# Automatically generated by qmake (3.0) Fri Feb 5 03:45:01 2016
######################################################################

TEMPLATE = app
TARGET = matrix_ui
INCLUDEPATH += .

# Input
QT += widgets
HEADERS += matrixwindow.h \
    matrixmodel.h \
    matrixDelegate.h
FORMS +=  matrixwindow.ui
SOURCES += main.cpp matrixwindow.cpp \
    matrixmodel.cpp \
    matrixDelegate.cpp
