/*
 * Author: Tashwin Khurana
 *
 * File Autogenerated by the Qt designer for the ui file
 *
 * Corresponding ui file: matrixwindow.ui
 *
 * Added Functionality to edit and compare multiple matrices 
 * loaded in using a csv file
 */

#ifndef matrixwindow_h
#define matrixwindow_h

#include "matrixmodel.h"
#include "matrixDelegate.h"

#include <QMainWindow>
#include <QStandardItemModel>
#include <QApplication>
#include <QHeaderView>
#include <QFileDialog>
#include <QTableView>
#include <QDebug>

namespace Ui {
class MatrixWindow;
}

class MatrixWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MatrixWindow(QWidget *parent = 0);
    ~MatrixWindow();

private:
    void setupUI();

private slots:
    void on_upload_clicked();

    void on_saveChanges_clicked();

    void on_upload_2_clicked();

    void on_saveChanges_2_clicked();

    void on_loadMultiple_clicked(bool checked);

    void on_compareRadioButton_clicked(bool checked);

    void on_editRadio_toggled(bool checked);

    void on_tableView_entered(const QModelIndex &index);

    void on_tableView_2_entered(const QModelIndex &index);

    void onError(const QString &msg);

    void on_prev_clicked();

    void on_next_clicked();

    void on_prev_2_clicked();

    void on_next_2_clicked();

private:
    Ui::MatrixWindow *ui;

    MatrixModel *model, *model_2;

    MatrixDelegate delegate, delegate_2;

     QMovie *movie;
};

#endif // MATRIXWINDOW_H
